export const state = {
  apiBase: sessionStorage.getItem("iposSaApiBase") || defaultApiBase(),
  session: null,
  page: document.body.dataset.page || "ALL",
};

export const pageMap = {
  ALL: "dashboard.html",
  ADMINISTRATOR: "admin.html",
  MANAGER: "manager.html",
  OPERATIONS_STAFF: "operations.html",
  ACCOUNTING_STAFF: "accounting.html",
  MERCHANT: "merchant.html",
};

export const profileDirectory = {
  Sysdba: ["System DBA", "sysdba@infopharma.local", "Administrator", "ADM-001"],
  manager: ["Director of Operations", "ops.director@infopharma.local", "Director of Operations", "MGR-001"],
  accountant: ["Senior Accountant", "accountant@infopharma.local", "Senior Accountant", "ACC-001"],
  clerk: ["Accounts Clerk", "clerk@infopharma.local", "Accountant", "ACC-002"],
  warehouse1: ["Warehouse Employee 1", "warehouse1@infopharma.local", "Warehouse Employee", "OPS-101"],
  warehouse2: ["Warehouse Employee 2", "warehouse2@infopharma.local", "Warehouse Employee", "OPS-102"],
  delivery: ["Delivery Team", "delivery@infopharma.local", "Delivery Department Employee", "OPS-103"],
  city: ["CityPharmacy", "citypharmacy@example.com", "Merchant Account", "ACC0001"],
  cosymed: ["Cosymed Ltd", "cosymed@example.com", "Merchant Account", "ACC0002"],
  hello: ["HelloPharmacy", "hello@example.com", "Merchant Account", "ACC0003"],
};

export const actionDescriptions = {
  loginAuthentication: "Authenticate and review subsystem user credentials.",
  listMerchants: "View all merchant accounts available to your role.",
  searchMerchants: "Search merchants by ID, name, email, or account status.",
  getMerchant: "Display merchant account details and current information.",
  createMerchant: "Create a new merchant account and linked user login.",
  updateMerchant: "Modify merchant detail records and account metadata.",
  deleteMerchant: "Delete an existing merchant account from the system.",
  listProducts: "Display the live product catalogue.",
  getProduct: "Retrieve one catalogue item in detail.",
  createProduct: "Add a new product to the catalogue.",
  updateProduct: "Modify an existing catalogue item.",
  deleteProduct: "Remove a catalogue item from the system.",
  restockProduct: "Add stock to an existing product.",
  setMinStock: "Update the minimum stock threshold for a product.",
  listUsers: "View all login users for the subsystem.",
  createUser: "Create a subsystem login account.",
  updateUser: "Update a subsystem login account and role assignment.",
  deleteUser: "Delete a subsystem login account.",
  merchantBalance: "Check the merchant balance and current account status.",
  viewMerchantReminders: "View reminder and account-warning information for the current merchant.",
  updateDiscount: "Change the merchant discount plan.",
  restoreMerchant: "Restore an account with manager approval.",
  reportLowStock: "Generate the low-stock catalogue report.",
  reportTurnover: "Generate the turnover report for a date range.",
  reportStockTurnover: "Generate the stock turnover report.",
  reportMerchantOrders: "Generate a merchant orders report.",
  reportMerchantActivity: "Generate a detailed merchant activity report.",
  reportMerchantInvoices: "Generate invoices for one merchant over a period.",
  reportCompanyInvoices: "Generate invoices across all merchants.",
  reportDebtorReminders: "Show current debtor reminders and overdue merchants.",
  integrationStatus: "Show the configured CA and PU integration endpoints for demo diagnostics.",
  sendCaStock: "Relay a stock item to Team B's IPOS-CA stock endpoint using the agreed contract.",
  sendPuMail: "Relay a mail request to Team C's IPOS-PU mail endpoint.",
  sendPuPayment: "Relay a payment request to Team C's IPOS-PU payment endpoint.",
  createApplication: "Record a new non-commercial application from the portal.",
  listApplications: "View submitted non-commercial applications.",
  approveApplication: "Approve an application and issue credentials.",
  rejectApplication: "Reject an application and log the decision.",
  listPendingOrders: "Display orders waiting for operational handling.",
  viewOrders: "Browse all orders or filter to pending ones.",
  searchOrders: "Search orders by ID and status.",
  getOrder: "Inspect a single order in full detail.",
  updateOrderStatus: "Change the order status through the dispatch workflow.",
  changeOrderStatus: "Accept a pending order or mark a dispatched order as delivered.",
  generateInvoice: "Generate and store the invoice for an order.",
  getInvoice: "Open a stored invoice.",
  printInvoice: "Open a printable invoice view.",
  listPayments: "Display recorded merchant payments.",
  recordPayment: "Record a card, bank transfer, or cheque payment.",
  searchProducts: "Search the catalogue by keyword.",
  createOrder: "Place a new merchant order against the current catalogue.",
  listMyOrders: "Display the current merchant's order history.",
  listMyInvoices: "Display invoices for the current merchant.",
};

export const actionIcons = {
  loginAuthentication: "L",
  listMerchants: "M",
  searchMerchants: "S",
  getMerchant: "V",
  createMerchant: "+",
  updateMerchant: "U",
  deleteMerchant: "-",
  listProducts: "P",
  getProduct: "V",
  createProduct: "+",
  updateProduct: "U",
  deleteProduct: "D",
  restockProduct: "R",
  setMinStock: "T",
  listUsers: "U",
  createUser: "+",
  updateUser: "E",
  deleteUser: "-",
  merchantBalance: "£",
  viewMerchantReminders: "!",
  updateDiscount: "%",
  restoreMerchant: "R",
  reportLowStock: "L",
  reportTurnover: "T",
  reportStockTurnover: "S",
  reportMerchantOrders: "O",
  reportMerchantActivity: "A",
  reportMerchantInvoices: "I",
  reportCompanyInvoices: "C",
  reportDebtorReminders: "D",
  integrationStatus: "I",
  sendCaStock: "C",
  sendPuMail: "M",
  sendPuPayment: "£",
  createApplication: "+",
  listApplications: "A",
  approveApplication: "Y",
  rejectApplication: "N",
  listPendingOrders: "P",
  viewOrders: "O",
  searchOrders: "S",
  getOrder: "O",
  updateOrderStatus: "U",
  changeOrderStatus: "U",
  generateInvoice: "I",
  getInvoice: "I",
  printInvoice: "P",
  listPayments: "£",
  recordPayment: "£",
  searchProducts: "S",
  createOrder: "O",
  listMyOrders: "O",
  listMyInvoices: "I",
};

export const roleModules = {
  ADMINISTRATOR: [
    // ========== USER MANAGEMENT ==========
    {
      pill: "Admin",
      desc: "Authenticate and manage subsystem users.",
      fields: [
        ["username", "Username", "demo_user"],
        ["password", "Password", "demo123"],
        ["role", "Role", "OPERATIONS_STAFF"],
      ],
      buttons: [
        ["Login Authentication", "loginAuthentication"],
        ["List All Users", "listUsers"],
        ["Create User Account", "createUser"],
        ["Delete User Account", "deleteUser"],
      ],
    },
    // ========== MERCHANT MANAGEMENT ==========
    {
      pill: "Admin",
      desc: "Create and manage merchant accounts.",
      fields: [
        ["merchantId", "Merchant ID", "ACC0004"],
        ["name", "Business Name", "New Pharmacy"],
        ["email", "Email", "newpharmacy@example.com"],
        ["password", "Password", "Welcome123!"],
        ["address", "Business Address", "123 High Street, London"],
        ["phone", "Phone Number", "020 1234 5678"],
        ["creditLimit", "Credit Limit (£)", "5000"],
        ["discountType", "Discount Type", "FIXED"],
        ["fixedDiscountRate", "Fixed Discount Rate (%)", "3"],
      ],
      buttons: [
        ["Create Merchant Account", "createMerchant"],
        ["Update Merchant Details", "updateMerchant"],
        ["View Merchant Information", "getMerchant"],
        ["Delete Merchant Account", "deleteMerchant"],
        ["Modify Merchant Settings", "updateDiscount"],
        ["Delete Discount Plan", "deleteDiscountPlan"],
        ["Restore Merchant from Default", "restoreMerchant"],
      ],
    },
    // ========== CATALOGUE MANAGEMENT ==========
    {
      pill: "Admin",
      desc: "Catalogue administration actions.",
      fields: [
        ["productId", "Product ID", "90000001"],
        ["name", "Product Name", "Demo Syrup"],
        ["packageType", "Package Type", "Box"],
        ["unit", "Unit", "Caps"],
        ["unitsInPack", "Units In Pack", "20"],
        ["unitPrice", "Unit Price", "9.99"],
        ["stockLevel", "Stock Level", "35"],
        ["minimumStockLevel", "Minimum Stock", "10"],
      ],
      buttons: [
        ["List All Products", "listProducts"],
        ["Create Catalogue Item", "createProduct"],
        ["Update Catalogue Item", "updateProduct"],
        ["View Catalogue Item", "getProduct"],
        ["Delete Catalogue Product", "deleteProduct"],
        ["Restock Product", "restockProduct"],
        ["Set Minimum Stock", "setMinStock"],
      ],
    },
    // ========== ORDER MANAGEMENT (Operations) ==========
    {
      pill: "Admin",
      desc: "Order processing and dispatch controls.",
      fields: [
        ["orderId", "Order ID", "1"],
        ["status", "Status", "DISPATCHED"],
        ["invoiceId", "Invoice ID", "1"],
        ["courier", "Courier", "DHL"],
        ["trackingNumber", "Tracking Number", "DHL-1001"],
        ["expectedDelivery", "Expected Delivery", "2026-03-28"],
        ["dispatchedBy", "Dispatched By", "delivery"],
      ],
      buttons: [
        ["View Orders", "viewOrders"],
        ["View Order Details", "getOrder"],
        ["Change Order Status", "changeOrderStatus"],
        ["Generate Invoice", "generateInvoice"],
      ],
    },
    // ========== PAYMENT MANAGEMENT (Accounting) ==========
    {
      pill: "Admin",
      desc: "Record merchant payments in different payment modes.",
      fields: [
        ["merchantId", "Merchant ID", "ACC0003"],
        ["amount", "Amount", "15.50"],
        ["method", "Method", "CARD"],
        ["reference", "Reference", "CARD-1002"],
      ],
      buttons: [
        ["List All Payments", "listPayments"],
        ["Record Card Payment", "recordPayment"],
        ["Record Bank Transfer", "recordPayment"],
        ["Record Cheque Payment", "recordPayment"],
        ["Merchant Balance", "merchantBalance"],
      ],
    },
    // ========== REPORTING ==========
    {
      pill: "Admin",
      desc: "Generate all system reports.",
      fields: [
        ["merchantId", "Merchant ID", "ACC0003"],
        ["start", "Start Date", "2026-03-01"],
        ["end", "End Date", "2026-03-31"],
      ],
      buttons: [
        ["Low Stock Report", "reportLowStock"],
        ["Turnover Report", "reportTurnover"],
        ["Stock Turnover Report", "reportStockTurnover"],
        ["Debtor Reminders", "reportDebtorReminders"],
        ["Merchant Orders Report", "reportMerchantOrders"],
        ["Merchant Activity Report", "reportMerchantActivity"],
        ["Merchant Invoices Report", "reportMerchantInvoices"],
        ["Company Invoices Report", "reportCompanyInvoices"],
      ],
    },
    // ========== NON-COMMERCIAL APPLICATIONS ==========
    {
      pill: "Admin",
      desc: "Non-commercial application decisions from the portal.",
      fields: [
        ["applicationEmail", "Application Email", "cool1@example.com"],
        ["memberType", "Member Type", "NON_COMMERCIAL"],
        ["accountNo", "Account No", "PU0004"],
        ["companyName", "Company Name", "Pond Pharmacy"],
        ["companyAddress", "Company Address", "Chislehurst, 25 High Street, BR7 5BN"],
        ["companyRegistration", "Company Registration", "UK10003429CompH"],
        ["applicationId", "Application ID", "1"],
      ],
      buttons: [
        ["Create Application", "createApplication"],
        ["List Applications", "listApplications"],
        ["Approve Application", "approveApplication"],
        ["Reject Application", "rejectApplication"],
      ],
    },
    // ========== INTEGRATION ==========
    {
      pill: "Admin",
      desc: "Cross-subsystem integration testing.",
      fields: [
        ["sender", "Mail Sender", "ipos-sa@londonsoftwarehouse.local"],
        ["receivers", "Mail Receivers JSON", '["cool@example.com"]', "textarea"],
        ["subject", "Mail Subject", "IPOS-SA integration test"],
        ["mailBody", "Mail Body", "Approved. Temporary password issued.", "textarea"],
        ["amount", "Payment Amount", "29.99"],
        ["senderName", "Sender Name", "Peter Popov"],
        ["senderCardNumber", "Sender Card Number", "0000 000000 0000 0001"],
        ["senderCVV", "Sender CVV", "3245"],
        ["senderExpiryDate", "Sender Expiry Date", "30/08/2030"],
        ["senderBillingAddress", "Sender Billing Address", "1 Demo Street, London"],
        ["senderEmail", "Sender Email", "cool@example.com"],
        ["receiverName", "Receiver Name", "InfoPharma Ltd"],
        ["receiverBankName", "Receiver Bank Name", "Demo Bank"],
        ["receiverAccountNumber", "Receiver Account Number", "12345678"],
        ["receiverSortCode", "Receiver Sort Code", "12-34-56"],
      ],
      buttons: [
        ["Integration Status", "integrationStatus"],
        ["Relay PU Mail", "sendPuMail"],
        ["Relay PU Payment", "sendPuPayment"],
        ["Relay CA Stock Sync", "sendCaStock"],
      ],
    },
  ],

  MANAGER: [
    {
      pill: "Manager",
      desc: "Create and manage merchant accounts (email is used for login)",
      fields: [
        ["merchantId", "Merchant ID", "ACC0004"],
        ["merchantSearch", "Merchant Search", "ACC0001"],
        ["name", "Business Name", "New Pharmacy"],
        ["email", "Email (Login Username)", "newpharmacy@example.com"],
        ["password", "Password", "Welcome123!"],
        ["address", "Business Address", "123 High Street, London"],
        ["phone", "Phone Number", "020 1234 5678"],
        ["creditLimit", "Credit Limit (£)", "5000"],
        ["discountType", "Discount Type", "FIXED"],
        ["fixedDiscountRate", "Fixed Discount Rate (%)", "3"],
      ],
      buttons: [
        ["Create New Merchant Account", "createMerchant"],
        ["Update Merchant Details", "updateMerchant"],
        ["List Merchants", "listMerchants"],
        ["Search Merchants", "searchMerchants"],
        ["View Merchant Information", "getMerchant"],
        ["View Merchant Balance", "merchantBalance"],
        ["Modify Merchant Settings", "updateDiscount"],
      ],
    },
    {
      pill: "Manager",
      desc: "Reporting and invoice actions required for the demo.",
      fields: [
        ["merchantId", "Merchant ID", "ACC0001"],
        ["invoiceId", "Invoice ID", "1"],
        ["start", "Start", "2026-03-01"],
        ["end", "End", "2026-03-31"],
      ],
      buttons: [
        ["Low Stock Report", "reportLowStock"],
        ["Turnover Report", "reportTurnover"],
        ["Stock Turnover Report", "reportStockTurnover"],
        ["Merchant Orders Report", "reportMerchantOrders"],
        ["Merchant Activity Report", "reportMerchantActivity"],
        ["Merchant Invoices Report", "reportMerchantInvoices"],
        ["Company Invoices Report", "reportCompanyInvoices"],
        ["Debtor Reminders Report", "reportDebtorReminders"],
        ["Display Invoice", "getInvoice"],
        ["Print Invoice", "printInvoice"],
      ],
    },
    {
      pill: "Manager",
      desc: "Non-commercial application decisions from the portal.",
      fields: [
        ["applicationEmail", "New Application Email", "cool1@example.com"],
        ["memberType", "Member Type", "NON_COMMERCIAL"],
        ["accountNo", "Account No", "PU0004"],
        ["companyName", "Company Name", "Pond Pharmacy"],
        ["companyAddress", "Company Address", "Chislehurst, 25 High Street, BR7 5BN"],
        ["companyRegistration", "Company Registration", "UK10003429CompH"],
        ["applicationId", "Application ID", "1"],
      ],
      buttons: [
        ["Create Application", "createApplication"],
        ["List Applications", "listApplications"],
        ["Approve Application", "approveApplication"],
        ["Reject Application", "rejectApplication"],
      ],
    },
    {
      pill: "Integration",
      desc: "Inspect and exercise the live subsystem REST links used on demo day.",
      fields: [
        ["sender", "Mail Sender", "ipos-sa@londonsoftwarehouse.local"],
        ["receivers", "Mail Receivers JSON", '["cool@example.com"]', "textarea"],
        ["subject", "Mail Subject", "IPOS-SA integration test"],
        ["mailBody", "Mail Body", "Approved. Temporary password issued.", "textarea"],
        ["amount", "Payment Amount", "29.99"],
        ["senderName", "Sender Name", "Peter Popov"],
        ["senderCardNumber", "Sender Card Number", "0000 000000 0000 0001"],
        ["senderCVV", "Sender CVV", "3245"],
        ["senderExpiryDate", "Sender Expiry Date", "30/08/2030"],
        ["senderBillingAddress", "Sender Billing Address", "1 Demo Street, London"],
        ["senderEmail", "Sender Email", "cool@example.com"],
        ["receiverName", "Receiver Name", "InfoPharma Ltd"],
        ["receiverBankName", "Receiver Bank Name", "Demo Bank"],
        ["receiverAccountNumber", "Receiver Account Number", "12345678"],
        ["receiverSortCode", "Receiver Sort Code", "12-34-56"],
      ],
      buttons: [
        ["Integration Status", "integrationStatus"],
        ["Relay PU Mail", "sendPuMail"],
        ["Relay PU Payment", "sendPuPayment"],
      ],
    },
    {
      pill: "Manager",
      desc: "Delete a merchant's discount plan",
      fields: [
        ["merchantId", "Merchant ID", ""]
      ],
      buttons: [["Delete Discount Plan", "deleteDiscountPlan"]],
    },
    {
      pill: "Manager",
      desc: "Restore merchant account from IN_DEFAULT to NORMAL/SUSPENDED (requires director approval)",
      fields: [
        ["merchantId", "Merchant ID", ""],
        ["newStatus", "New Status", "NORMAL"]
      ],
      buttons: [["Restore Merchant from Default", "restoreMerchant"]],
    },
  ],
  OPERATIONS_STAFF: [
    {
      pill: "Operations",
      desc: "Dispatch and order status controls.",
      fields: [
        ["orderId", "Order ID", "1"],
        ["status", "Status", "DISPATCHED"],
        ["invoiceId", "Invoice ID", "1"],
        ["courier", "Courier", "DHL"],
        ["trackingNumber", "Tracking Number", "DHL-1001"],
        ["expectedDelivery", "Expected Delivery", "2026-03-28"],
        ["dispatchedBy", "Dispatched By", "delivery"],
      ],
      buttons: [
        ["View Orders", "viewOrders"],
        ["View Order Details", "getOrder"],
        ["Enter Dispatch Details", "updateOrderStatus"],
        ["Change Order Status", "changeOrderStatus"],
        ["Generate Invoice", "generateInvoice"],
        ["View Invoice", "getInvoice"],
      ],
    },
    {
      pill: "Integration",
      desc: "Review the current subsystem integration targets while demonstrating delivery flow.",
      fields: [
        ["name", "Product Name", "Aspirin"],
        ["packageType", "Package Type", "BOX"],
        ["units", "Units", "CAPS"],
        ["unitsInAPack", "Units In Pack", "20"],
        ["bulkCost", "Bulk Cost", "0.50"],
        ["markupRate", "Markup Rate", "2"],
        ["quantity", "Quantity", "10"],
        ["stockLimit", "Stock Limit", "15"],
      ],
      buttons: [["Integration Status", "integrationStatus"], ["Relay CA Stock Sync", "sendCaStock"]],
    },
  ],
  ACCOUNTING_STAFF: [
    {
      pill: "Accounting",
      desc: "Record merchant payments in different payment modes.",
      fields: [
        ["merchantId", "Merchant ID", "ACC0003"],
        ["amount", "Amount", "15.50"],
        ["method", "Method", "CARD"],
        ["reference", "Reference", "CARD-1002"],
      ],
      buttons: [
        ["Record Card Payment", "recordPayment"],
        ["Record Bank Transfer", "recordPayment"],
        ["Record Cheque Payment", "recordPayment"],
        ["Merchant Balance", "merchantBalance"],
      ],
    },
    {
      pill: "Accounting",
      desc: "Review overdue debtors and invoice output.",
      fields: [
        ["merchantId", "Merchant ID", "ACC0001"],
        ["invoiceId", "Invoice ID", "1"],
        ["start", "Start", "2026-03-01"],
        ["end", "End", "2026-03-31"],
      ],
      buttons: [
        ["View Merchant Balance", "merchantBalance"],
        ["Debtor Reminders Report", "reportDebtorReminders"],
        ["View Invoice", "getInvoice"],
        ["Print Invoice", "printInvoice"],
      ],
    },
  ],
  MERCHANT: [
    {
      pill: "Catalogue",
      desc: "Browse and search the product catalogue.",
      fields: [
        ["search", "Search Products", ""],
      ],
      buttons: [
        ["View All Products", "listProducts"],
        ["Search Products", "searchProducts"],
      ],
    },
    {
      pill: "Orders",
      desc: "Place new orders and track existing ones.",
      fields: [],
      buttons: [
        ["Place New Order", "createOrder"],
        ["View My Orders", "listMyOrders"],
      ],
    },
    {
      pill: "Invoices",
      desc: "View and print your invoices.",
      fields: [
        ["invoiceId", "Invoice ID", ""],
      ],
      buttons: [
        ["View My Invoices", "listMyInvoices"],
        ["View Invoice", "getInvoice"],
        ["Print Invoice", "printInvoice"],
      ],
    },
    {
      pill: "Account",
      desc: "Manage your merchant account.",
      fields: [],
      buttons: [
        ["View Balance", "merchantBalance"],
        ["View Account Status", "getMerchant"],
        ["View Reminders", "viewMerchantReminders"],
      ],
    },
  ],
};

function defaultApiBase() {
  if (window.location.protocol.startsWith("http")) return `${window.location.origin}/api`;
  return "http://localhost:8080/api";
}
